version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat clean check --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9

matrix:
  fast_finish: true